Fix the following pip3 errors when installing required packages:
```
ERROR: tensorflow-gpu 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but
you'll have numpy 1.19.4 which is incompatible.

ERROR: Could not find a version that satisfies the requirement cProfile (from
-r requirements_local_tts.txt (line 12)) (from versions: none)
ERROR: No matching distribution found for cProfile (from -r
requirements_local_tts.txt (line 12))
```

cProfile should be included in Python, although it's possible
that there are OS incompatibilities with this assumption...